# Generated by Django 4.2 on 2024-06-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0003_alter_vendor_user"),
        ("store", "0004_wishlist_review_productfaq_notification_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
