# Generated by Django 4.2 on 2024-06-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
