# Generated by Django 4.2 on 2024-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "rate",
                    models.IntegerField(
                        default=7,
                        help_text="Numbers given here are in percentage. E.g 8%",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Taxes",
                "ordering": ["country"],
            },
        ),
    ]
